Задание 1.
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [14]:
import numpy as np

In [29]:
N = int(input('Введите значение N: '))
a = np.arange(N-1, -1, -1)
print(a)

Введите значение N: 10
[9 8 7 6 5 4 3 2 1 0]


Задание 2.
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [43]:
N = int(input('Введите значение N: '))
diag = np.diag(np.arange(N-1, -1, -1), k=0)
sum_ = sum(sum(diag))
print(' ')
print(diag)
print(f'\nСумма значений на диагронали = {sum_}\n')

Введите значение N: 11
 
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]

Сумма значений на диагронали = 55



Задание 3.
Решите систему уравнений:
4x + 2y + z = 4 , 
x + 3y = 12 , 
5y + 4z = -3 .

In [ ]:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [48]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array( [4, 12, -3] )
res = linalg.solve(a, b)

#Проверка
if np.allclose( np.dot(a, linalg.solve(a, b)), b ) == True:
    print(res)
else:
    print('Error')

[ 0.46666667  3.84444444 -5.55555556]
